### ISSUE TITLE
Schrödinger Cube lets lasers through

### ISSUE THREAD

**Issue by RobinRattus** [AxoLabs/BEE2-Axos-Packages#7] opened 2023-03-27 22:20 UTC
### BEEMod version
2.4.43.0

### UCP version
1.5 beta 7

### Describe the bug
A catcher Schrödinger Cube turns on emitter Schrödinger Cubes, however the laser still comes out of the other side.

### Steps to reproduce
Place Schrödinger Cubes and laser
Activate Schrödinger Catcher
Laser goes through AND emitter cube turns on

### Additional Information
It does not make sense for the laser to go through if it comes out of the other cube.

**Comment by AxoLabs** [comment] 2023-03-28 15:48
Reopening this, because while it ***is*** the intended behaviour, it is not the ideal one, so I may look into finding a way to fix this.

**Comment by AxoLabs** [comment] 2023-04-02 19:02
A fix has been implemented, closing the issue.

**Closed by AxoLabs** 2023-04-02 19:02 UTC
Labels: Enhancement, Implemented
